name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Test
        run: make test
      - name: Bench
        run: make bench > bench.txt; cat bench.txt
      - uses: actions/upload-artifact@v3
        with:
          name: bench.txt
          path: bench.txt
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
